/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sena;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import confi.Conexion;
import javax.swing.JOptionPane;

/**
 *
 * @author X555L
 */
public class Cargar extends javax.swing.JFrame {

    private Timer t;
    private ActionListener ac;
    private int x = 0;

    public Cargar() {
        initComponents();
        this.setLocationRelativeTo(null);

        ac = new ActionListener() {
            Conexion con = new Conexion();
            int a = con.x;

            @Override
            public void actionPerformed(ActionEvent e) {
                if (a == 1) {
                    x = x + 1;
                    jProgressBar_cargar.setValue(x);
                    if (jProgressBar_cargar.getValue() == 1) {
                        jLabel_cargar.setText("Cargando class Inicio.java");
                        //Inicio ini = new Inicio();

                    }
                    if (jProgressBar_cargar.getValue() == 2) {
                        jLabel_cargar.setText("Cargando class menu.java");
                        for (int i = 0; i < 10; i++) {
                        }
                    }
                    if (jProgressBar_cargar.getValue() == 3) {
                        jLabel_cargar.setText("Cargando class profes.java");
                        for (int i = 0; i < 5; i++) {
                        }
                    }
                    if (jProgressBar_cargar.getValue() == 4) {
                        jLabel_cargar.setText("Cargando class estudiantes.java");
                        for (int i = 0; i < 10; i++) {
                        }
                    }
                    if (jProgressBar_cargar.getValue() == 5) {
                        jLabel_cargar.setText("Cargando class salones.java");
                        for (int i = 0; i < 10; i++) {
                        }
                    }
                    if (jProgressBar_cargar.getValue() == 6) {
                        jLabel_cargar.setText("Cargando class sedes.java");
                        for (int i = 0; i < 10; i++) {
                        }
                    }
                    if (jProgressBar_cargar.getValue() == 7) {
                        jLabel_cargar.setText("Cargando class Conexion.java");
                        for (int i = 0; i < 10; i++) {
                        }
                    }
                    if (jProgressBar_cargar.getValue() > 7 && jProgressBar_cargar.getValue() < 11) {
                        jLabel_cargar.setText("Conectando con la BD");
                        //confi.Conexion con = new confi.Conexion();
                        Inicio ini = new Inicio();
                        ini.setVisible(true);
                        ini.setLocationRelativeTo(null);
                        dispose();
                        t.stop();
                    }
                } else if (a == 0) {
                    JOptionPane.showMessageDialog(null, "Error de carga", "ERROR", JOptionPane.ERROR_MESSAGE);
                }

            }
        };
        t = new Timer(200, ac);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar_cargar = new javax.swing.JProgressBar();
        jLabel_cargar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jProgressBar_cargar.setForeground(new java.awt.Color(0, 255, 255));
        jProgressBar_cargar.setMaximum(10);

        jLabel_cargar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_cargar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBar_cargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jLabel_cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel_cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jProgressBar_cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cargar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cargar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_cargar;
    private javax.swing.JProgressBar jProgressBar_cargar;
    // End of variables declaration//GEN-END:variables
}
