/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sena;

import javax.swing.JTextField;
import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author X555L
 */
public class Inicio extends javax.swing.JFrame {

    public Inicio() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_el_colegio = new javax.swing.JLabel();
        jButton_ingreso = new javax.swing.JButton();
        jLabel_fondo_inicio = new javax.swing.JLabel();
        jLabel_error = new javax.swing.JLabel();
        jTextField_user_login = new javax.swing.JTextField();
        jPasswordField_contrasena_login = new javax.swing.JPasswordField();
        jLabel_usuario_login = new javax.swing.JLabel();
        jLabel_contraseña_login = new javax.swing.JLabel();
        jLabel_error_2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_el_colegio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_el_colegio.setText("El colegio");

        jButton_ingreso.setBackground(new java.awt.Color(204, 204, 204));
        jButton_ingreso.setText("Ingresar");
        jButton_ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ingresoActionPerformed(evt);
            }
        });
        jButton_ingreso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_ingresoKeyPressed(evt);
            }
        });

        jLabel_fondo_inicio.setBackground(new java.awt.Color(0, 0, 255));
        jLabel_fondo_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sena/multimedia/colegio.jpg"))); // NOI18N

        jLabel_error.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel_error.setForeground(new java.awt.Color(255, 51, 51));

        jTextField_user_login.setBackground(new java.awt.Color(240, 240, 240));
        jTextField_user_login.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_user_login.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jTextField_user_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_user_loginActionPerformed(evt);
            }
        });

        jPasswordField_contrasena_login.setBackground(new java.awt.Color(240, 240, 240));
        jPasswordField_contrasena_login.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPasswordField_contrasena_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_contrasena_loginActionPerformed(evt);
            }
        });

        jLabel_usuario_login.setText("Nombre de usuario");

        jLabel_contraseña_login.setText("Contraseña");

        jLabel_error_2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel_error_2.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel_fondo_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel_el_colegio)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_usuario_login)
                            .addComponent(jTextField_user_login)
                            .addComponent(jButton_ingreso, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(jPasswordField_contrasena_login)
                            .addComponent(jLabel_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_contraseña_login)
                            .addComponent(jLabel_error_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(59, 59, 59))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel_el_colegio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_usuario_login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_user_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel_contraseña_login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField_contrasena_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_error, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_error_2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton_ingreso)
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_fondo_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ingresoActionPerformed
        // TODO add your handling code here:
        String user = "Santiago", pass = "1234";
        String user_ing, pass_ing;

        user_ing = jTextField_user_login.getText();
        pass_ing = new String(jPasswordField_contrasena_login.getPassword());

        if (user.equals(user_ing) && pass.equals(pass_ing)) {
            JOptionPane.showMessageDialog(null, "Bienvenido " + user, "Bienvendo", JOptionPane.PLAIN_MESSAGE);
            menu run = new menu();
            run.setVisible(true);
            run.setLocationRelativeTo(null);
            dispose();
        } else {
            jLabel_error.setText("Usuario y contraseña no coinsiden.");
            jLabel_error_2.setText("Vuelva a intentarlo");
            jTextField_user_login.setText("");
            jPasswordField_contrasena_login.setText("");
        }
        //pass_ing = jPasswordField_pass_login.getPassword();

    }//GEN-LAST:event_jButton_ingresoActionPerformed

    private void jPasswordField_contrasena_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_contrasena_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_contrasena_loginActionPerformed

    private void jTextField_user_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_user_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_user_loginActionPerformed

    private void jButton_ingresoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_ingresoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ingresoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ingreso;
    private javax.swing.JLabel jLabel_contraseña_login;
    private javax.swing.JLabel jLabel_el_colegio;
    private javax.swing.JLabel jLabel_error;
    private javax.swing.JLabel jLabel_error_2;
    private javax.swing.JLabel jLabel_fondo_inicio;
    private javax.swing.JLabel jLabel_usuario_login;
    private javax.swing.JPasswordField jPasswordField_contrasena_login;
    private javax.swing.JTextField jTextField_user_login;
    // End of variables declaration//GEN-END:variables
}
