/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sena;

/**
 *
 * @author X555L
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_bienvenido_menu = new javax.swing.JLabel();
        jButton_sede_menu = new javax.swing.JButton();
        jButton_salon_menu = new javax.swing.JButton();
        jButton_estudiante_menu = new javax.swing.JButton();
        jButton_profesores_menu = new javax.swing.JButton();
        jLabel_fondo_menu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_bienvenido_menu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_bienvenido_menu.setText("¡Bienvenido!");

        jButton_sede_menu.setBackground(new java.awt.Color(204, 204, 204));
        jButton_sede_menu.setText("Sedes");
        jButton_sede_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sede_menuActionPerformed(evt);
            }
        });

        jButton_salon_menu.setBackground(new java.awt.Color(204, 204, 204));
        jButton_salon_menu.setText("Salones");
        jButton_salon_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salon_menuActionPerformed(evt);
            }
        });

        jButton_estudiante_menu.setBackground(new java.awt.Color(204, 204, 204));
        jButton_estudiante_menu.setText("Estudiantes");
        jButton_estudiante_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_estudiante_menuActionPerformed(evt);
            }
        });

        jButton_profesores_menu.setBackground(new java.awt.Color(204, 204, 204));
        jButton_profesores_menu.setText("Profesores");
        jButton_profesores_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_profesores_menuActionPerformed(evt);
            }
        });

        jLabel_fondo_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sena/multimedia/colegio.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_fondo_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel_bienvenido_menu))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_estudiante_menu, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(jButton_sede_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_profesores_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_salon_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel_bienvenido_menu)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_sede_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_salon_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_profesores_menu, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jButton_estudiante_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(69, Short.MAX_VALUE))
            .addComponent(jLabel_fondo_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_sede_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sede_menuActionPerformed
        sedes run = new sedes();
        run.setVisible(true);
        run.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButton_sede_menuActionPerformed

    private void jButton_salon_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salon_menuActionPerformed
        // TODO add your handling code here:
        salones run = new salones();
        run.setVisible(true);
        run.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButton_salon_menuActionPerformed

    private void jButton_estudiante_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_estudiante_menuActionPerformed
        // TODO add your handling code here:
        estudiantes run = new estudiantes();
        run.setVisible(true);
        run.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButton_estudiante_menuActionPerformed

    private void jButton_profesores_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_profesores_menuActionPerformed
        // TODO add your handling code here:
        profes run = new profes();
        run.setVisible(true);
        run.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButton_profesores_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_estudiante_menu;
    private javax.swing.JButton jButton_profesores_menu;
    private javax.swing.JButton jButton_salon_menu;
    private javax.swing.JButton jButton_sede_menu;
    private javax.swing.JLabel jLabel_bienvenido_menu;
    private javax.swing.JLabel jLabel_fondo_menu;
    // End of variables declaration//GEN-END:variables
}
