/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sena;

import confi.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author X555L
 */
public class sedes extends javax.swing.JFrame {

    Conexion cone = new Conexion();
    Connection cnn;
    DefaultTableModel model;
    Statement st;
    ResultSet rs;
    int idc;

    /**
     * Creates new form sedes
     */
    public sedes() {
        initComponents();
        setLocationRelativeTo(null);
        consultar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_sede = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_sede = new javax.swing.JTable();
        jTextField_dir_sede = new javax.swing.JTextField();
        jLabel_text_nueva_sede = new javax.swing.JLabel();
        jTextField_ingreso_sede = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton_crear_sede = new javax.swing.JButton();
        jButton_actualizar_sede = new javax.swing.JButton();
        jButton_eliminar_sede = new javax.swing.JButton();
        jButton_sede_to_menu = new javax.swing.JButton();
        jLabel_fondo_sede = new javax.swing.JLabel();
        jLabel_id_sede = new javax.swing.JLabel();
        jTextField_id_sede = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_sede.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel_sede.setText("¡SEDES!");

        jTable_sede.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_sede", "Nombre", "Direccion"
            }
        ));
        jTable_sede.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_sedeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_sede);

        jLabel_text_nueva_sede.setText("Ingrese nueva sede");

        jLabel1.setText("Ingrese la direccion");

        jButton_crear_sede.setBackground(new java.awt.Color(0, 153, 0));
        jButton_crear_sede.setForeground(new java.awt.Color(255, 255, 255));
        jButton_crear_sede.setText("Crear");
        jButton_crear_sede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_crear_sedeActionPerformed(evt);
            }
        });

        jButton_actualizar_sede.setBackground(new java.awt.Color(0, 0, 153));
        jButton_actualizar_sede.setForeground(new java.awt.Color(255, 255, 255));
        jButton_actualizar_sede.setText("Actualizar");
        jButton_actualizar_sede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizar_sedeActionPerformed(evt);
            }
        });

        jButton_eliminar_sede.setBackground(new java.awt.Color(153, 0, 0));
        jButton_eliminar_sede.setForeground(new java.awt.Color(255, 255, 255));
        jButton_eliminar_sede.setText("Eliminar");
        jButton_eliminar_sede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminar_sedeActionPerformed(evt);
            }
        });

        jButton_sede_to_menu.setBackground(new java.awt.Color(153, 153, 153));
        jButton_sede_to_menu.setText("Regresar");
        jButton_sede_to_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sede_to_menuActionPerformed(evt);
            }
        });

        jLabel_fondo_sede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sena/multimedia/colegio.jpg"))); // NOI18N

        jLabel_id_sede.setText("ID Sede");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_fondo_sede, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                        .addComponent(jLabel_sede, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton_actualizar_sede, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23)
                                        .addComponent(jButton_crear_sede, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton_eliminar_sede, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel_text_nueva_sede))
                                            .addComponent(jLabel_id_sede))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField_ingreso_sede)
                                            .addComponent(jTextField_dir_sede, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                            .addComponent(jTextField_id_sede)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jButton_sede_to_menu)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_sede_to_menu)
                .addGap(10, 10, 10)
                .addComponent(jLabel_sede)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_id_sede)
                    .addComponent(jTextField_id_sede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel_text_nueva_sede))
                    .addComponent(jTextField_ingreso_sede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_dir_sede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_actualizar_sede)
                    .addComponent(jButton_crear_sede)
                    .addComponent(jButton_eliminar_sede))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addComponent(jLabel_fondo_sede, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_sede_to_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sede_to_menuActionPerformed
        // TODO add your handling code here:
        menu run = new menu();
        run.setVisible(true);
        run.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButton_sede_to_menuActionPerformed

    private void jButton_actualizar_sedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizar_sedeActionPerformed
        // TODO add your handling code here:
        modificar();
        consultar();
        jTextField_dir_sede.setText("");
        jTextField_id_sede.setText("");
        jTextField_ingreso_sede.setText("");
    }//GEN-LAST:event_jButton_actualizar_sedeActionPerformed

    //METODO MODIFICAR
    void modificar() {
        int id = Integer.parseInt(jTextField_id_sede.getText());
        String nom = jTextField_ingreso_sede.getText();
        String dir = jTextField_dir_sede.getText();

        try {
            String sql = "UPDATE sede SET ID_sede='" + idc + "', Nombre_sede='" + nom + "', Direccion_sede='" + dir + "' WHERE ID_sede=" + idc;

            cnn = cone.getConnection();
            st = cnn.createStatement();
            st.executeUpdate(sql);
            System.out.println("Sede actualizada");
            limpiarTabla();
        } catch (Exception e) {
        }
    }
    //METODO MODIFICAR FIN


    private void jButton_crear_sedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_crear_sedeActionPerformed
        // TODO add your handling code here:
        crear();
        consultar();
        jTextField_dir_sede.setText("");
        jTextField_id_sede.setText("");
        jTextField_ingreso_sede.setText("");
    }//GEN-LAST:event_jButton_crear_sedeActionPerformed

    private void jTable_sedeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_sedeMouseClicked
        // TODO add your handling code here:
        //CREACION CLICK PARA ACTUALIZAR
        int fila = jTable_sede.getSelectedRow();
        if (fila == -1) {
            System.out.print("No se selecciono ninguna fila");
            limpiarTabla();
        } else {
            idc = Integer.parseInt((String) jTable_sede.getValueAt(fila, 0).toString());
            String nom = (String) jTable_sede.getValueAt(fila, 1);
            String dir = (String) jTable_sede.getValueAt(fila, 2);
            jTextField_id_sede.setText("" + idc);
            jTextField_ingreso_sede.setText("" + nom);
            jTextField_dir_sede.setText("" + dir);
        } //CREACION CLICK PARA ACTUALIZAR FIN
    }//GEN-LAST:event_jTable_sedeMouseClicked

    private void jButton_eliminar_sedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminar_sedeActionPerformed
        // TODO add your handling code here:
        eliminar();
        consultar();
        jTextField_dir_sede.setText("");
        jTextField_id_sede.setText("");
        jTextField_ingreso_sede.setText("");
    }//GEN-LAST:event_jButton_eliminar_sedeActionPerformed

    void eliminar() {
        int fila = jTable_sede.getSelectedRow();
        try {
            if (fila == -1) {
                System.out.print("No se selecciono ninguna fila");
                limpiarTabla();
            } else {
                String sql = "DELETE FROM sede WHERE ID_sede="+idc;
                cnn = cone.getConnection();
                st = cnn.createStatement();
                st.executeUpdate(sql);
                System.out.println("Sede eliminada");
                limpiarTabla();
            }
        } catch (Exception e) {
        }
       
    } //CREACION CLICK PARA ACTUALIZAR FIN

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sedes().setVisible(true);
            }
        });
    }

    //METODO DE CREAR
    void crear() {
        int id = Integer.parseInt(jTextField_id_sede.getText());
        String nom = jTextField_ingreso_sede.getText();
        String dir = jTextField_dir_sede.getText();

        try {
            String sql = "INSERT INTO sede VALUE('" + id + "' , '" + nom + "' , '" + dir + "')";

            cnn = cone.getConnection();
            st = cnn.createStatement();
            st.executeUpdate(sql);
            System.out.println("Sede creada");
            limpiarTabla();
        } catch (Exception e) {
        }

    }

    void limpiarTabla() {
        for (int i = 0; i <= jTable_sede.getRowCount(); i++) {
            model.removeRow(i);
            i = i - 1;
        }
    }
    //METODO CREAR FIN

    //METODO CONSULTAR
    void consultar() {
        String sql = "select * from sede";

        try {
            cnn = cone.getConnection();
            st = cnn.createStatement();
            rs = st.executeQuery(sql);

            Object[] sede = new Object[3];
            model = (DefaultTableModel) jTable_sede.getModel();

            while (rs.next()) {
                sede[0] = rs.getInt("ID_sede");
                sede[1] = rs.getString("Nombre_sede");
                sede[2] = rs.getString("Direccion_sede");

                model.addRow(sede);
            }
            jTable_sede.setModel(model);
            System.out.println("Sede consultada");
        } catch (Exception e) {
        }
    }
    //METODO CONSULTAR FIN


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_actualizar_sede;
    private javax.swing.JButton jButton_crear_sede;
    private javax.swing.JButton jButton_eliminar_sede;
    private javax.swing.JButton jButton_sede_to_menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_fondo_sede;
    private javax.swing.JLabel jLabel_id_sede;
    private javax.swing.JLabel jLabel_sede;
    private javax.swing.JLabel jLabel_text_nueva_sede;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_sede;
    private javax.swing.JTextField jTextField_dir_sede;
    private javax.swing.JTextField jTextField_id_sede;
    private javax.swing.JTextField jTextField_ingreso_sede;
    // End of variables declaration//GEN-END:variables
}
